language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get install libproj-dev proj-bin proj-data
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
  - sudo dpkg -i libproj9_4.9.2-2_amd64.deb 
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_4.9.2-2_amd64.deb
  - sudo dpkg -i libproj-dev_4.9.2-2_amd64.deb
  - sudo apt-get install libgeos-dev
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
#   - sudo apt-get install python-numpy python3-numpy
#   - sudo apt-get install python-scipy python3-scipy
#   - sudo apt-get install python-requests python3-requests
#   - sudo apt-get install python-pillow python3-pillow
#   - sudo apt-get install python-pyresample python3-pyresample
#   - sudo apt-get install python-configparser

script: 
  - python setup.py develop
  - python setup.py build
  - python setup.py install
  - pip install cython
  - pip install pyproj
  - pip install -e .[debug_cartopy]
  - create_map -h
